FROM oven/bun:1

RUN useradd -m -u 1002 -g 1000 llm

USER llm

WORKDIR /app

COPY --chown=llm:bm24 package.json bun.lock ./

RUN bun install

COPY --chown=llm:bm24 server.js ./server.js

EXPOSE 5005

CMD ["bun", "server.js"]
