services:
  caddy:
    image: caddy:2.8-alpine
    container_name: caddy
    networks:
      - bm24-internal
      - bm24-public
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

networks:
  bm24-public:
    driver: bridge
  bm24-internal:
    external: true
# create the local network before starting the containers:
# docker network create --driver bridge --internal bm24-internal
