services:
  bm24:
    build: .
    container_name: bm24
    ports:
      - "3000:3000"
    networks:
      - bm24

  llm-service:
    build: ./llm-service
    container_name: llm-service
    ports:
      - "5005:5005"
    networks:
      - bm24

networks:
  bm24:
    driver: bridge
