FROM oven/bun:1 AS Build

RUN groupadd -g 1000 bm24 && useradd -m -u 1001 -g bm24 next

USER next

WORKDIR /app

COPY --chown=next:bm24 . .

RUN bun install

RUN bun run build


FROM oven/bun:1 AS Production

RUN groupadd -g 1000 bm24 && useradd -m -u 1001 -g bm24 next

USER next

WORKDIR /app

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

EXPOSE 3000

CMD ["bun", "server.js"]