FROM oven/bun:1 AS Build

WORKDIR /app

COPY --chown=next:bm24 . .

RUN bun install

RUN bun run build


FROM oven/bun:1 AS Production

WORKDIR /app

RUN groupadd bm24 && useradd -m -g bm24 next

USER next

COPY --from=build --chown=next:bm24 /app/.next/standalone ./
COPY --from=build --chown=next:bm24 /app/.next/static ./.next/static
COPY --from=build --chown=next:bm24 /app/public ./public

EXPOSE 3000

CMD ["bun", "server.js"]