name: Build Test

on:
    pull_request:
        types: ["opened"]
        branches:
            - "main"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install Next.js dependencies
              working-directory: bm24/next-frontend
              run: bun install

            - name: Build bm24
              working-directory: bm24
              run: bun run build
